In [14]:
X=sol.x

FStar=X.reshape(3,3)
print FStar
print La.det(FStar)
F=La.inv(FStar.T)

print F
print La.det(F)
Fd=F/(np.abs(La.det(F)))**(1/3.0)

print La.det(Fd)


GK=La.polar(Fd)

print GK[1]

Eig=La.eig(GK[1])


V=Eig[1].T
D=np.eye(3,3)

D[0,0]=np.real(Eig[0][0])
D[1,1]=np.real(Eig[0][1])
D[2,2]=np.real(Eig[0][2])
print D
print La.norm(V[:,2])

D[0,0],D[1,1],D[2,2]=np.sqrt(D[0,0]),np.sqrt(D[1,1]),np.sqrt(D[2,2])

print D

Usqrt=np.dot(V,D)
Usqrt=np.dot(Usqrt,La.inv(V))

print Usqrt

STensor=Usqrt-np.eye(3,3)

print STensor

[[  1.00040664e+00  -6.58806474e-04  -7.23712674e-04]
 [ -7.35499961e-04   9.97777445e-01  -3.81303211e-03]
 [  5.94108162e-04   5.01779075e-04   1.00215183e+00]]
1.00033295966
[[  9.99593583e-01   7.34572697e-04  -5.92959351e-04]
 [  6.59641337e-04   1.00222607e+00  -5.02207305e-04]
 [  7.24375045e-04   3.81384506e-03   9.97850450e-01]]
0.999667151168
1.0
[[  9.99704746e-01   6.98460073e-04   6.43971609e-05]
 [  6.98460073e-04   1.00234322e+00   1.65103664e-03]
 [  6.43971609e-05   1.65103664e-03   9.97960120e-01]]
[[ 1.0030357   0.          0.        ]
 [ 0.          0.99957617  0.        ]
 [ 0.          0.          0.99739622]]
1.0
[[ 1.0015167   0.          0.        ]
 [ 0.          0.99978806  0.        ]
 [ 0.          0.          0.99869726]]
[[  9.99756266e-01   3.83640295e-04  -2.89044382e-04]
 [  3.83640295e-04   1.00141875e+00   2.57700568e-04]
 [ -2.89044382e-04   2.57700568e-04   9.98827009e-01]]
[[-0.00024373  0.00038364 -0.00028904]
 [ 0.00038364  0.00141875  0.0002577